services:
  - type: web
    name: taskmanager
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PORT
        value: "10000"
      - key: IP
        value: "0.0.0.0"
      - key: DEBUG
        value: "False"
